
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* font
* filename: /home/david/MyFont.xml
* name: MyFont
* family: Ubuntu
* size: 8
* style: Thin
* included characters: ═║╒╓╔╕╖╗╘╙╚╛╜╠╡╢╣╤╥╦╧╨╩╪╫╬╝╞╟
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
* compacted: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/
#include <stdint.h>

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
 typedef struct {
     long int code;
     const tImage *image;
     const int image_left;
     const int image_top;
     const int char_width;
     const int char_height;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;


#define FIX_ZERO_LENGTH(length) (length==0?1:length)



#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29590[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29590 = { image_data_MyFont_0xe29590,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29591[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29591 = { image_data_MyFont_0xe29591,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29592[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙████
    // ∙∙∙∙████
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    0x00, 0x00, 0x00, 0x0f, 0x0f, 0x08, 0x08, 0x08
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29592 = { image_data_MyFont_0xe29592,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29593[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x1f, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29593 = { image_data_MyFont_0xe29593,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29594[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█████
    // ∙∙∙█████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x00, 0x00, 0x00, 0x1f, 0x1f, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29594 = { image_data_MyFont_0xe29594,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29595[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ████∙∙∙∙
    // ████∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    0x00, 0x00, 0x00, 0xf0, 0xf0, 0x10, 0x10, 0x10
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29595 = { image_data_MyFont_0xe29595,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29596[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █████∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x00, 0x00, 0x00, 0x00, 0xf8, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29596 = { image_data_MyFont_0xe29596,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29597[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █████∙∙∙
    // █████∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x00, 0x00, 0x00, 0xf8, 0xf8, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29597 = { image_data_MyFont_0xe29597,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29598[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙████
    // ∙∙∙∙████
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x08, 0x08, 0x08, 0x0f, 0x0f, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29598 = { image_data_MyFont_0xe29598,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe29599[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█████
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x18, 0x18, 0x18, 0x18, 0x1f, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe29599 = { image_data_MyFont_0xe29599,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe2959a[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█████
    // ∙∙∙█████
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x18, 0x18, 0x18, 0x1f, 0x1f, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe2959a = { image_data_MyFont_0xe2959a,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe2959b[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ████∙∙∙∙
    // ████∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x10, 0x10, 0x10, 0xf0, 0xf0, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe2959b = { image_data_MyFont_0xe2959b,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe2959c[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // █████∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x18, 0x18, 0x18, 0x18, 0xf8, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe2959c = { image_data_MyFont_0xe2959c,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe2959d[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // █████∙∙∙
    // █████∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x18, 0x18, 0x18, 0xf8, 0xf8, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe2959d = { image_data_MyFont_0xe2959d,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe2959e[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙████
    // ∙∙∙∙████
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    0x08, 0x08, 0x08, 0x0f, 0x0f, 0x08, 0x08, 0x08
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe2959e = { image_data_MyFont_0xe2959e,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe2959f[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0x18, 0x1f, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe2959f = { image_data_MyFont_0xe2959f,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a0[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█████
    // ∙∙∙█████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0x1f, 0x1f, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a0 = { image_data_MyFont_0xe295a0,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a1[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ████∙∙∙∙
    // ████∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    0x10, 0x10, 0x10, 0xf0, 0xf0, 0x10, 0x10, 0x10
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a1 = { image_data_MyFont_0xe295a1,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a2[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // █████∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0x18, 0xf8, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a2 = { image_data_MyFont_0xe295a2,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a3[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // █████∙∙∙
    // █████∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0xf8, 0xf8, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a3 = { image_data_MyFont_0xe295a3,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a4[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ████████
    // ████████
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0x10, 0x10
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a4 = { image_data_MyFont_0xe295a4,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a5[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ████████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x00, 0x00, 0x00, 0x00, 0xff, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a5 = { image_data_MyFont_0xe295a5,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a6[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ████████
    // ████████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a6 = { image_data_MyFont_0xe295a6,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a7[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x10, 0x10, 0x10, 0xff, 0xff, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a7 = { image_data_MyFont_0xe295a7,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a8[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ████████
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x18, 0x18, 0x18, 0x18, 0xff, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a8 = { image_data_MyFont_0xe295a8,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295a9[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x18, 0x18, 0x18, 0xff, 0xff, 0x00, 0x00, 0x00
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295a9 = { image_data_MyFont_0xe295a9,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295aa[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ████████
    // ████████
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    0x10, 0x10, 0x10, 0xff, 0xff, 0x10, 0x10, 0x10
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295aa = { image_data_MyFont_0xe295aa,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295ab[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ████████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0x18, 0xff, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295ab = { image_data_MyFont_0xe295ab,
    0, 0, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_MyFont_0xe295ac[FIX_ZERO_LENGTH(8)] = {
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ████████
    // ████████
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0xff, 0xff, 0x18, 0x18, 0x18
#if 0 == 8
    0xff
#endif
};
static const tImage MyFont_0xe295ac = { image_data_MyFont_0xe295ac,
    0, 0, 8};
#endif


static const tChar MyFont_array[] = {

#if (0x0 == 0x0)
  // character: '═'
  {0xe29590, &MyFont_0xe29590, 0, 0, 8, 8 },
#else
  // character: '═' == ''
  {0xe29590, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '║'
  {0xe29591, &MyFont_0xe29591, 0, 0, 8, 8 },
#else
  // character: '║' == ''
  {0xe29591, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╒'
  {0xe29592, &MyFont_0xe29592, 0, 0, 8, 8 },
#else
  // character: '╒' == ''
  {0xe29592, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╓'
  {0xe29593, &MyFont_0xe29593, 0, 0, 8, 8 },
#else
  // character: '╓' == ''
  {0xe29593, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╔'
  {0xe29594, &MyFont_0xe29594, 0, 0, 8, 8 },
#else
  // character: '╔' == ''
  {0xe29594, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╕'
  {0xe29595, &MyFont_0xe29595, 0, 0, 8, 8 },
#else
  // character: '╕' == ''
  {0xe29595, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╖'
  {0xe29596, &MyFont_0xe29596, 0, 0, 8, 8 },
#else
  // character: '╖' == ''
  {0xe29596, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╗'
  {0xe29597, &MyFont_0xe29597, 0, 0, 8, 8 },
#else
  // character: '╗' == ''
  {0xe29597, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╘'
  {0xe29598, &MyFont_0xe29598, 0, 0, 8, 8 },
#else
  // character: '╘' == ''
  {0xe29598, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╙'
  {0xe29599, &MyFont_0xe29599, 0, 0, 8, 8 },
#else
  // character: '╙' == ''
  {0xe29599, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╚'
  {0xe2959a, &MyFont_0xe2959a, 0, 0, 8, 8 },
#else
  // character: '╚' == ''
  {0xe2959a, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╛'
  {0xe2959b, &MyFont_0xe2959b, 0, 0, 8, 8 },
#else
  // character: '╛' == ''
  {0xe2959b, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╜'
  {0xe2959c, &MyFont_0xe2959c, 0, 0, 8, 8 },
#else
  // character: '╜' == ''
  {0xe2959c, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╝'
  {0xe2959d, &MyFont_0xe2959d, 0, 0, 8, 8 },
#else
  // character: '╝' == ''
  {0xe2959d, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╞'
  {0xe2959e, &MyFont_0xe2959e, 0, 0, 8, 8 },
#else
  // character: '╞' == ''
  {0xe2959e, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╟'
  {0xe2959f, &MyFont_0xe2959f, 0, 0, 8, 8 },
#else
  // character: '╟' == ''
  {0xe2959f, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╠'
  {0xe295a0, &MyFont_0xe295a0, 0, 0, 8, 8 },
#else
  // character: '╠' == ''
  {0xe295a0, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╡'
  {0xe295a1, &MyFont_0xe295a1, 0, 0, 8, 8 },
#else
  // character: '╡' == ''
  {0xe295a1, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╢'
  {0xe295a2, &MyFont_0xe295a2, 0, 0, 8, 8 },
#else
  // character: '╢' == ''
  {0xe295a2, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╣'
  {0xe295a3, &MyFont_0xe295a3, 0, 0, 8, 8 },
#else
  // character: '╣' == ''
  {0xe295a3, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╤'
  {0xe295a4, &MyFont_0xe295a4, 0, 0, 8, 8 },
#else
  // character: '╤' == ''
  {0xe295a4, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╥'
  {0xe295a5, &MyFont_0xe295a5, 0, 0, 8, 8 },
#else
  // character: '╥' == ''
  {0xe295a5, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╦'
  {0xe295a6, &MyFont_0xe295a6, 0, 0, 8, 8 },
#else
  // character: '╦' == ''
  {0xe295a6, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╧'
  {0xe295a7, &MyFont_0xe295a7, 0, 0, 8, 8 },
#else
  // character: '╧' == ''
  {0xe295a7, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╨'
  {0xe295a8, &MyFont_0xe295a8, 0, 0, 8, 8 },
#else
  // character: '╨' == ''
  {0xe295a8, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╩'
  {0xe295a9, &MyFont_0xe295a9, 0, 0, 8, 8 },
#else
  // character: '╩' == ''
  {0xe295a9, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╪'
  {0xe295aa, &MyFont_0xe295aa, 0, 0, 8, 8 },
#else
  // character: '╪' == ''
  {0xe295aa, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╫'
  {0xe295ab, &MyFont_0xe295ab, 0, 0, 8, 8 },
#else
  // character: '╫' == ''
  {0xe295ab, &MyFont_0x, 0, 0, 8, 8 },
#endif

#if (0x0 == 0x0)
  // character: '╬'
  {0xe295ac, &MyFont_0xe295ac, 0, 0, 8, 8 }
#else
  // character: '╬' == ''
  {0xe295ac, &MyFont_0x, 0, 0, 8, 8 }
#endif

};


const tFont MyFont = { 29, MyFont_array };


#undef FIX_ZERO_LENGTH
